// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggypbisikjjqwgzbnapx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneXBiaXNpa2pqcXdnemJuYXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4Nzg0OTgsImV4cCI6MjA0OTQ1NDQ5OH0.1sK1s0i9LB_7sWsM43_V1_d1ichOp6yHWLIfE2P_qEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);